---
title: "20160919基礎操作"
author: "Luke Fan"
date: "2016年9月26日"
output: html_document
---
## R Output
```{r}
x = rnorm(20)
y = rnorm(20) 
lm.result = lm(y ~ x)
names(lm.result)
lm.result$coefficients
```

```{r}
x = c(1,2,3)
y = c(11,12,13)

for (i in 1:3)
{
   x[i] = x[i]+100
}
x

# User defined function: f1
f1 = function(a,b){
   c = a+b
   return(c)
}

# Now  a = x, b = y
z = f1(x,y)     

if  (is.vector(z)) {
   cat("z is a vector! \n")
} else {
   cat("z is NOT a vector! \n")
}

fit = lm(y ~ x)   # Simple regression
summary(fit)
```


## R Example 1
```{r}
# the scores and sexes of 6 students，stored in scores and  gender  vector variable
scores = c(60,55,64,66,55,56)

gender = c("male","male","female","frmale","male","female")
scores[2]

# 2:4 = c(2,3,4), the 2,3,4 elements
scores[2:4]

# the 1,3,4, 5 elements of scores
scores[c(1,3,4,5)]
scores[scores > 60]

# compute the average
mean(scores)

# compute the standard deviation
sd(scores) 
```

## R Example 
```{r}
# compute variance
var(scores)

# compute the median
median(scores)

# compute the 25th Percentile
quantile(scores,0.25)

scores[gender == "male"]
mean(scores[gender == "male"])

table(gender, scores)

hist(scores)       # histogram
```



